### ISSUE TITLE
[Bug] base-material-card loses rounded corners and has different padding with Vuetify 2.1

### ISSUE THREAD

**Issue by subn3t** [creativetimofficial/ct-vuetify-material-dashboard-pro#11]
### Version
1.0.3
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
Win 10
### Device
PC
### Browser & Version
Latest Chrome
### Steps to reproduce
1. npm update vuetify
2. open dashboard
### What is expected?
Dashboard looks the same
### What is actually happening?
Dashboard does not look the same

---

**Comment by mehdirochdi** [comment]
look at src/components/base/Materialcard.vue
add style="border-radius:6px"
`<v-sheet
        v-else
        :class="{ 'pa-7': !$slots.image }"
        :color="color"
        :max-height="icon ? 90 : undefined"
        :width="inline || icon ? 'auto' : '100%'"
        style="border-radius:6px"
        class="text-start v-card--material__heading mb-n6"
        dark>`

**Comment by marcpaskell** [comment]
looks like the border radius is due to a change in 2.1.4
https://github.com/vuetifyjs/vuetify/commit/487ebfe5ad892685d650cf308fa30e494507936a

you could add in a variable override
$sheet-border-radius: 4px;

nb. the only way I could get this to work was to rename main.scss to variables.scss and make the appropriate changes to vue.config.js

**Comment by johnleider** [comment]
this has been resolved for next release.
