### ISSUE TITLE
[Bug] App doesnt start in Edge browser

### ISSUE THREAD

**Issue by msmola726** [creativetimofficial/ct-vuetify-material-dashboard-pro#15]
### Version
1.0.3
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
Windows 10
### Device
laptop
### Browser & Version
Microsoft Edge 44.18362.387.0
### Steps to reproduce
1. open in edge
### What is expected?
app would start
### What is actually happening?
blank screen and app error in console

---

**Comment by zherman91** [comment]
Until the Chromium based Edge comes out of beta and becomes the actual version, you'll have to manually add the poly fills in order to get any Vue app with Vuex to work in Edge. I just recently did this and would like to mention that Edge does not provide an optimal experience, yet. I'm eager for the chromium version so we no longer have to use these poly fills. Does this help?

You can reference this as your leisure. https://cli.vuejs.org/guide/browser-compatibility.html

**Comment by msmola726** [comment]
It does thank you, based on what im finding, multiple sources say that it will be release somewhere in early 2020. Will there be any significant changes in the template that you guys already envision for Edge Chromium? I'm asking because we are penciled in for our release early 2020 as well, so im trying to gather some info to set proper expectations.

**Comment by zherman91** [comment]
I cant speak to what they have in mind for the template but i can assure you that the template as it is now, will work in the chromium version of Edge. If you want to be sure, you can try downloading the Edge beta and try it out. For the time being, and to at least show something on the screen when using Edge, you can add the poly fills in. This is what i did and put a disclaimer in my project that checks if Edge is being used and states that its an unsupported browser to the end user. Like i said, the current Edge is not optimal but it at least loads. Let me know if you have any other questions.

**Comment by johnleider** [comment]
resolved for next release.
