### ISSUE TITLE
[Bug] Text and Cards way too different from demo

### ISSUE THREAD

**Issue by camassucato** [creativetimofficial/ct-vuetify-material-dashboard-pro#16]
### Version
1.0.3
### Reproduction link
http://157.245.80.246/#/
### Operating System
MacOSX 10.14.6
### Device
Macbook Pro
### Browser & Version
Chrome Version 77.0.3865.90
### Steps to reproduce
Just open the reproduction link.
### What is expected?
On demo of the vuetify-material-dashboard-pro, all letters and fonts looks nice and not oversized. 
### What is actually happening?
On many devices and builds created, the dist build looks oversized and desproporcional. Cards titles, cards numbers and others components looks too much bigger than original demo of the kit.

---
### Solution
No solution yet.

**Comment by camassucato** [comment]
<img width="1143" alt="Screen Shot 2019-10-15 at 14 10 27" src="https://user-images.githubusercontent.com/686594/66853409-9b672e80-ef55-11e9-8dae-cef44df8affc.png">

**Comment by camassucato** [comment]
![1](https://user-images.githubusercontent.com/686594/66854997-cc952e00-ef58-11e9-9e29-65a40087c355.png)
![2](https://user-images.githubusercontent.com/686594/66854999-cc952e00-ef58-11e9-843e-9ac5e39f1c98.png)
![4](https://user-images.githubusercontent.com/686594/66855000-cc952e00-ef58-11e9-901e-1b57cf11ecb9.png)
![3](https://user-images.githubusercontent.com/686594/66855001-cc952e00-ef58-11e9-9034-9062370eac05.png)

**Comment by glinsky** [comment]
Look at the different props in classes "display"

It was 
![image](https://user-images.githubusercontent.com/28813341/66916602-3b8b8900-f024-11e9-82b2-cc19b90882e0.png)

has become 
![image](https://user-images.githubusercontent.com/28813341/66916793-a89f1e80-f024-11e9-93d7-ec187da34675.png)

This happened due to an update vuetify?

**Comment by dragosct** [comment]
Hi! Thank you for using our products and sorry for the late response. This is happening because in the package.json all the dependencies are automatically updated to the latest versions when you run the npm install. We will do a quick update with this. To fix the problem you must remove in package.json the sign `^`  from all dependencies (ex. "vue": "^2.6.10" ). After this you must delete your `package-lock.json` and `node_modules` and run again npm install, now this should work for you. 

Regards, 
Dragos

**Comment by single-page** [comment]
Hi, Dragos!
I did this, but an error comes up. If you remove the line with an error in the main.scss file, then the styles are still not correct.

![image](https://user-images.githubusercontent.com/48788140/66992843-389ba180-f0d3-11e9-9d8d-73c0d57f46d0.png)

package.json

![image](https://user-images.githubusercontent.com/48788140/66993120-ba8bca80-f0d3-11e9-863a-b204fee0f818.png)

Tell me, please, in which folder are the styles for display-2
I can't find them =(

![image](https://user-images.githubusercontent.com/48788140/66993501-57e6fe80-f0d4-11e9-922e-c669d3b585b4.png)

**Comment by camassucato** [comment]
Dragos. I received the same instruction via premium support (zendesk) and too many other problems occours after that. I think some one need to apply some attention on that matter...

**Comment by dragosct** [comment]
Hi there! We are sorry for this. My colleague @johnleider will fix these issues and we will make an update soon. 

Thank you for your understanding!

Regards, 
Dragos

**Comment by razvanioan** [comment]
Same here !

It seems that the CSS is totally different (font size, border radius and more)

It needs a proper fix, not sticking to exact dependency versions as we might want / need to update them in the near future !

**Comment by johnleider** [comment]
this is resolved for next release.

**Comment by single-page** [comment]
when is the release planned?
