### ISSUE TITLE
[Bug] Scrolling in pages, such as login, lock, register (again)

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#33]
### Version
Version 2.1.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/
### Operating System
Windows 10
### Device
PC
### Browser & Version
Firefox 70, Chrome 76
### Steps to reproduce
Just navigate to login pages
### What is expected?
All links and elements are in the page without scrolling
### What is actually happening?
the page is not fitting the screen in terms of height, I should scroll down to see the footer

---
### Additional comments
This issue was in v1.0.0 and [fixed in 1.0.1](https://github.com/creativetimofficial/ct-vuetify-material-dashboard-pro/issues/2). Now it back again.
![image](https://user-images.githubusercontent.com/54809428/73723441-1a1ced00-473a-11ea-9f25-29c06fabdd06.png)

**Comment by phillipa-llama** [comment]
I noticed this as well and presumed it was part of the fix for #20 in v2.1.0
I think the issue is being cause by the  v-responsive__sizer adding additional padding to the bottom of the screen, because when I remove it it works perfectly, but can't find where it is being generated from:

![image](https://user-images.githubusercontent.com/57439980/73723892-ca86f300-4732-11ea-8220-26a9fb875e79.png)

**Comment by nonoodles** [comment]
Same issue with the update, its on the CT demo site as well.

**Comment by johnleider** [comment]
Looking into it.

**Comment by johnleider** [comment]
Can you upgrade to the latest Vuetify version (v2.2.11) and see if the issue persists?

**Comment by phillipa-llama** [comment]
@johnleider I have tested with Vuetify v2.2.11 (previously we were using v2.2.8) this morning and the issue still persists. The only way I can get our login screen to load on Desktop with no scrolling is to remove the v-responsive__sizer div in Chrome tools after it has loaded. 

Let me know if you require screenshots/recording.

**Comment by johnleider** [comment]
I'm still having issues reproducing this. Need more precise steps. A video may help, but keep in mind additional info will probably be needed. Thank you!

**Comment by nonoodles** [comment]
> 
> 
> I'm still having issues reproducing this. Need more precise steps. A video may help, but keep in mind additional info will probably be needed. Thank you!

@johnleider - Reproduction is easy. @OdiljonQurbon gave an accurate account of what the problem is I am not sure what you are struggling with.

navigate to : https://www.creative-tim.com/product/vuetify-material-dashboard-pro

Click on "Live Preview"

Navigate to the login page template. You will notice the scrollbar on the right, and the footer placed well below the bottom of the page instead of adjusting the element to the height of the page.

![creativetim](https://user-images.githubusercontent.com/37075087/80457479-ab61c100-892f-11ea-9aff-b4e80c39ed5a.png)

I have this morning again downloaded a clean copy of the dashboard from creative tim. The issue persists even with vuetify 2.2.25.

**Comment by johnleider** [comment]
Resolved. Will be out with next release.
