### ISSUE TITLE
Updates promised, never released

### ISSUE THREAD

**Issue by nonoodles** [creativetimofficial/ct-vuetify-material-dashboard-pro#40]
All the issues on this repo were closed over a month ago stating they will be fixed in the upcoming release. To date nothing has been released.

How much complaining does one person have to do to get their bugs fixed on the premium template they have bought?

**Comment by nonoodles** [comment]
https://github.com/creativetimofficial/ct-vuetify-material-dashboard-pro/issues/37

More disgruntled customers

**Comment by dragosct** [comment]
Hi, @nonoodles! Thanks for using our products and sorry for the late response. We will do the update these days, we have a very very busy period and we are sorry that the update was not published like we sad. 

Thanks for your understanding! 

Regards,
Dragos

**Comment by nonoodles** [comment]
@dragosct10 @timcreative  @johnleider 

We are now a further 2 weeks down the line, when is this update coming?

**Comment by pilotkid** [comment]
@nonoodles It will never come. Maybe try pushing for a refund. I was lucky and jumped ship early on, but the lack of support for this product is insane. Especially when you paid for "premium support". Back when I commented in issue #37 all I got was @dragosct10 sales pitch. When it comes to a product when your customers beg for support and you ignore them can that be classified as "support"? 

![image](https://user-images.githubusercontent.com/6385285/87750120-d386f080-c7b7-11ea-9ff2-489bc231cfa5.png)
![image](https://user-images.githubusercontent.com/6385285/87750138-e00b4900-c7b7-11ea-98ff-29cecb134e69.png)

--

Also after a quick read through the reviews, let's be honest do you think they really have a legitimate 4.9 stars? Considering that there are no reviews below 5 stars, and all the comments just read "design quality" and are written in broken English if they go beyond two words?

![image](https://user-images.githubusercontent.com/6385285/87750318-55771980-c7b8-11ea-8eab-07bb31978fd8.png)
![image](https://user-images.githubusercontent.com/6385285/87750361-77709c00-c7b8-11ea-9a64-f8779b758e0f.png)
![image](https://user-images.githubusercontent.com/6385285/87750447-b272cf80-c7b8-11ea-9cb0-43ea59022fce.png)

Also, we should look at the (apparently sole) project maintainer's commit history of @dragosct10 
![image](https://user-images.githubusercontent.com/6385285/87752011-96712d00-c7bc-11ea-9b06-288062112ef5.png)

Clearly it looks like some really exciting updates are just around the corner.

**Comment by pilotkid** [comment]
> @dragosct10 @timcreative @johnleider
> 
> We are now a further 2 weeks down the line, when is this update coming?

I am genuinely shocked there was an update. See #43.

**Comment by johnleider** [comment]
I've addressed the meat of this issue in #43. Any additional conversation related to the updated version should be directed there.

Thank you for your patience.

**Comment by nonoodles** [comment]
@johnleider You have previously closed the tickets that were open stating that there was an upcoming release. @dragosct10 has also promised updates "in coming days" a month ago.

This ticket should stay open until you have fixed up the bugs in this template and @timcreative are providing premium support which has been paid for. People who are interested in buying this template should be aware of the issues it has.

@pilotkid The review system is fake on @timcreative . I left an honest 2 star review for this template and it did not show.

**Comment by devlinpadayachee** [comment]
This is a piece of shit. I wasted my money on this. At this point I can build a better template than this.

**Comment by johnleider** [comment]
I'm locking this thread as the conversation is derogatory and not helpful. I have addressed the concerns in #43 and encourage any further on discussion (constructive) go there.

**Comment by alexandru-paduraru** [comment]
@nonoodles @pilotkid @johnleider @dragosct10 hi guys. Here is Alex, the co-founder o Creative Tim.

First of all I want to say sorry for the bad experience you got using our product. I know there were a lot of inconsistencies between what we prepared inside our team and what we delivered. As Pilotkid said he already got a refund. If there is somebody else who want a refund we will proceed with that and you can keep the product and the license till we will release the version that @johnleider is writing now. We basically rewrite the whole product from scratch.

To give some inside information. We are a small team of 12 persons (including our partner John) who deliver 110 products for hundred of thousands and millions of developers around the world. Sometimes bad things happen, things that we can’t control. The COVID situation got our team to have many changes and a lot of restructures had to be done. 

While we create new products, from which 70% are open source and have between 2-8.000 stars on github we also do support for the premium ones and we also have many attacks. As John said we had to stop requesting money for premium support as we could deliver premium support because of the high number of requests we had. We are doing changes there too to continue provide what we promise.

On the reviews problems: in the last month we had 9000 attacks on our products live previews, database and internal servers. We have a lot of attackers that try to cheat our review systems giving hundreds of 1*-2* reviews just to push down our products on google search. Here is an example: https://imgur.com/g9SpiJX that’s why the reviews are delayed some times. They have those 2 words as when we request a review we let people choose from a preselected menu: https://imgur.com/YApZhKv and the text area message is optional.

The framework that @johnleider created has on its own 1 million downloads each month, and he dedicate 99% of its time to support that framework which is used for free. He is also pushing hard to deliver the products we have created together and also the support. 

I just wanted to give some more details to understand what we do, that we have good intentions to provide the best products and we are not a scam. But sometimes the odds are against us. Please follow the details on this thread #43 and we will have more updates there. 

Thank you for understanding.

Best,
Alex
